#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by package_release.py; upgrades an existing systemd installation.
RELEASE_ID="@@RELEASE_ID@@"
SOURCE_COMMIT="@@SOURCE_COMMIT@@"
ARCHIVE_NAME="@@ARCHIVE_NAME@@"
EXPECTED_SHA256="@@SHA256@@"
PUBLIC_ORIGIN="${1:-https://www.nicokara.icu}"
APP_ROOT="/data/nicokara"
SHARED="$APP_ROOT/shared"
ENV_FILE="$SHARED/nicokara.env"
RELEASE_DIR="$APP_ROOT/releases/$RELEASE_ID"
BACKUP_DIR="$APP_ROOT/backups/$RELEASE_ID"
ARCHIVE_PATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/$ARCHIVE_NAME"
TIMEOUT_DROPIN="/etc/systemd/system/nicokara-backend.service.d/stop-timeout.conf"

fail() { echo "错误：$*" >&2; exit 1; }
[[ $EUID -eq 0 ]] || fail "请使用 root 或 sudo bash 执行。"
[[ "$PUBLIC_ORIGIN" =~ ^https?://[A-Za-z0-9._-]+(:[0-9]{1,5})?$ ]] || fail "网站地址格式错误。"
for executable in python3 node ffmpeg curl tar sha256sum systemctl nginx flock readlink install runuser; do
  command -v "$executable" >/dev/null || fail "缺少命令：$executable"
done
python3 -c 'import sys; assert sys.version_info >= (3, 11)' || fail "需要 Python 3.11 或以上。"
node -e 'const [a,b]=process.versions.node.split(".").map(Number);if(a<22||(a===22&&b<13))process.exit(1)' || fail "需要 Node.js 22.13 或以上，建议 24。"
[[ -f "$ARCHIVE_PATH" && -f "$ENV_FILE" && -L "$APP_ROOT/current" ]] || fail "需要部署包及现有 /data/nicokara 服务。"
PREVIOUS_RELEASE="$(readlink -f "$APP_ROOT/current")"
OLD_PYTHON="$PREVIOUS_RELEASE/backend/.venv/bin/python"
[[ -x "$OLD_PYTHON" ]] || fail "旧版本 Python 环境不存在。"
if [[ "$PREVIOUS_RELEASE" == "$RELEASE_DIR" ]]; then
  fail "发布目录就是当前运行版本，不能原地覆盖；请重新生成部署包。"
fi
archive_existing_directory() {
  local path="$1"
  local parent="$2"
  local archived
  local suffix
  [[ "$path" != "$parent" && "$path" == "$parent/"* ]] || fail "拒绝操作目录：$path"
  [[ ! -L "$path" ]] || fail "发布目录不能是符号链接：$path"
  if [[ -e "$path" ]]; then
    [[ -d "$path" ]] || fail "发布目录不是目录：$path"
    suffix="$(date +%Y%m%d-%H%M%S)-$$"
    archived="$path.previous-$suffix"
    while [[ -e "$archived" ]]; do
      suffix="$(date +%Y%m%d-%H%M%S)-$RANDOM"
      archived="$path.previous-$suffix"
    done
    mv -- "$path" "$archived"
    echo "已有目录已保留为：$archived"
  fi
  mkdir -p "$path"
}
archive_existing_directory "$RELEASE_DIR" "$APP_ROOT/releases"
archive_existing_directory "$BACKUP_DIR" "$APP_ROOT/backups"
for unit in nicokara-backend nicokara-frontend; do
  [[ "$(systemctl show -p LoadState --value "$unit")" == "loaded" ]] || fail "服务不存在：$unit"
done
nginx -t
printf '%s  %s\n' "$EXPECTED_SHA256" "$ARCHIVE_PATH" | sha256sum -c -
exec 9>"$APP_ROOT/deploy.lock"
flock -n 9 || fail "已有部署任务正在执行。"

# Resolve the configured database without displaying credentials.
DATA_DIR="$("$OLD_PYTHON" - "$ENV_FILE" "$SHARED/data" <<'PY'
import sys
from pathlib import Path
from dotenv import dotenv_values
value = dotenv_values(sys.argv[1]).get('NICOKARA_DATA_DIR') or sys.argv[2]
path = Path(value)
if not path.is_absolute():
    raise SystemExit('NICOKARA_DATA_DIR must be absolute for this upgrade script')
print(path)
PY
)"
DATABASE="$DATA_DIR/nicokara.sqlite3"
[[ -f "$DATABASE" ]] || fail "找不到现有数据库。"
check_idle() {
  "$OLD_PYTHON" - "$DATABASE" <<'PY'
import sqlite3, sys
from pathlib import Path
with sqlite3.connect(Path(sys.argv[1]).as_uri() + '?mode=ro', uri=True) as db:
    active = db.execute("SELECT count(*) FROM jobs WHERE status IN ('UPLOADED', 'PROCESSING')").fetchone()[0]
if active:
    raise SystemExit(f'仍有 {active} 个等待或处理中的任务，请完成后再部署。')
PY
}
check_idle

mkdir -p "$RELEASE_DIR" "$BACKUP_DIR"
chmod 700 "$BACKUP_DIR"
SERVICES_STOPPED=false
SWITCHED=false
CONFIG_CHANGED=false
DROPIN_EXISTED=false

atomic_current() {
  ln -sfn "$1" "$APP_ROOT/current-$RELEASE_ID.tmp"
  mv -Tf "$APP_ROOT/current-$RELEASE_ID.tmp" "$APP_ROOT/current"
}
rollback() {
  local code=$?
  trap - ERR INT TERM
  set +e
  if [[ "$SWITCHED" == true ]]; then
    systemctl stop nicokara-frontend nicokara-backend
    atomic_current "$PREVIOUS_RELEASE"
  fi
  if [[ "$CONFIG_CHANGED" == true ]]; then
    cp -p "$BACKUP_DIR/nicokara.env" "$ENV_FILE"
    if [[ "$DROPIN_EXISTED" == true ]]; then
      cp -p "$BACKUP_DIR/stop-timeout.conf" "$TIMEOUT_DROPIN"
    else
      rm -f "$TIMEOUT_DROPIN"
    fi
    systemctl daemon-reload
  fi
  if [[ "$SERVICES_STOPPED" == true ]]; then
    systemctl start nicokara-backend nicokara-frontend
  fi
  echo "升级失败，已尝试恢复旧版本：$PREVIOUS_RELEASE" >&2
  echo "备份目录：$BACKUP_DIR；数据库和任务文件未被回滚或删除。" >&2
  exit "${code:-1}"
}
trap rollback ERR
trap 'false' INT TERM

# Reject traversal and link entries before extracting.
python3 - "$ARCHIVE_PATH" "$RELEASE_DIR" <<'PY'
import sys, tarfile
from pathlib import PurePosixPath
with tarfile.open(sys.argv[1], 'r:gz') as archive:
    for member in archive.getmembers():
        p = PurePosixPath(member.name)
        if p.is_absolute() or '..' in p.parts or not p.parts or p.parts[0] != 'nicokara':
            raise SystemExit('Unsafe archive member')
        if not (member.isfile() or member.isdir()):
            raise SystemExit('Archive links and devices are not supported')
PY
tar -xzf "$ARCHIVE_PATH" -C "$RELEASE_DIR" --strip-components=1 --no-same-owner
[[ "$(cat "$RELEASE_DIR/SOURCE_COMMIT.txt")" == "$SOURCE_COMMIT" ]]
(cd "$RELEASE_DIR" && sha256sum --quiet -c FILE_SHA256SUMS)

echo "安装新版本 Python 依赖，旧服务此时继续运行。"
python3 -m venv "$RELEASE_DIR/backend/.venv"
PYTHON="$RELEASE_DIR/backend/.venv/bin/python"
export PIP_CACHE_DIR="$SHARED/cache/pip"
mkdir -p "$PIP_CACHE_DIR"
PIP_INDEX="${NICOKARA_PIP_INDEX_URL:-https://pypi.org/simple}"
"$PYTHON" -m pip install --disable-pip-version-check --timeout 120 --retries 3 --index-url "$PIP_INDEX" --upgrade pip
TORCH_VARIANT=cpu
if command -v nvidia-smi >/dev/null && nvidia-smi -L >/dev/null 2>&1; then TORCH_VARIANT=cu126; fi
"$PYTHON" -m pip install --disable-pip-version-check --timeout 120 --retries 3 \
  --index-url "https://download.pytorch.org/whl/$TORCH_VARIANT" \
  "torch==2.7.1+$TORCH_VARIANT" "torchaudio==2.7.1+$TORCH_VARIANT" "torchvision==0.22.1+$TORCH_VARIANT"
"$PYTHON" -m pip install --disable-pip-version-check --timeout 120 --retries 3 \
  --index-url "$PIP_INDEX" -e "$RELEASE_DIR/backend[ai]"
"$PYTHON" -c 'import app.main, torch, torchaudio, faster_whisper, audio_separator; assert hasattr(torchaudio.pipelines, "MMS_FA")'
chmod -R a+rX "$RELEASE_DIR"

# Preserve the live announcement and worker settings.
if [[ -f "$SHARED/announcement.json" ]]; then
  ln -sfn "$SHARED/announcement.json" "$RELEASE_DIR/frontend/public/announcement.json"
fi
if [[ -f "$SHARED/workers.toml" ]]; then cp -p "$SHARED/workers.toml" "$BACKUP_DIR/workers.toml"; fi
if [[ -f "$SHARED/announcement.json" ]]; then cp -p "$SHARED/announcement.json" "$BACKUP_DIR/announcement.json"; fi
cp -p "$ENV_FILE" "$BACKUP_DIR/nicokara.env"
systemctl cat nicokara-backend >"$BACKUP_DIR/backend.service.txt"
systemctl cat nicokara-frontend >"$BACKUP_DIR/frontend.service.txt"
if [[ -f "$TIMEOUT_DROPIN" ]]; then
  cp -p "$TIMEOUT_DROPIN" "$BACKUP_DIR/stop-timeout.conf"
  DROPIN_EXISTED=true
fi

check_idle
SERVICES_STOPPED=true
systemctl stop nicokara-frontend nicokara-backend
# Catch tasks accepted during the stop window. Restart the old service on failure.
check_idle
"$OLD_PYTHON" - "$DATABASE" "$BACKUP_DIR/nicokara.sqlite3" <<'PY'
import sqlite3, sys
with sqlite3.connect(sys.argv[1]) as src, sqlite3.connect(sys.argv[2]) as dst:
    src.backup(dst)
PY
CONFIG_CHANGED=true
"$PYTHON" - "$ENV_FILE" "$PUBLIC_ORIGIN" "$TIMEOUT_DROPIN" <<'PY'
import math, sys
from pathlib import Path
from dotenv import dotenv_values, set_key
env, origin, dropin = sys.argv[1:]
values = dotenv_values(env)
defaults = {'NICOKARA_MAX_ACTIVE_JOBS': '32', 'NICOKARA_MAX_UPLOAD_SESSIONS': '32',
            'NICOKARA_MIN_FREE_DISK_BYTES': '2147483648', 'NICOKARA_SHUTDOWN_TIMEOUT_SECONDS': '30'}
for key, value in defaults.items():
    if key not in values:
        set_key(env, key, value, quote_mode='never')
if 'NICOKARA_ALLOWED_ORIGINS' not in values:
    set_key(env, 'NICOKARA_ALLOWED_ORIGINS', origin, quote_mode='never')
timeout = float(values.get('NICOKARA_SHUTDOWN_TIMEOUT_SECONDS', '30'))
if not math.isfinite(timeout) or timeout < 0:
    raise SystemExit('Invalid shutdown timeout')
target = Path(dropin)
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(f'[Service]\nTimeoutStopSec={max(45, math.ceil(timeout) + 15)}\n')
PY
chown www-data:www-data "$ENV_FILE"
chmod 640 "$ENV_FILE"
SWITCHED=true
atomic_current "$RELEASE_DIR"
systemctl daemon-reload
systemctl start nicokara-backend nicokara-frontend
READY=false
for attempt in {1..90}; do
  if systemctl is-active --quiet nicokara-backend nicokara-frontend \
    && curl --fail --silent --max-time 3 --output /dev/null http://127.0.0.1:8000/health \
    && curl --fail --silent --max-time 3 --output /dev/null http://127.0.0.1:3000/; then
    READY=true
    break
  fi
  sleep 1
done
[[ "$READY" == true ]] || { echo "新版本健康检查失败。" >&2; false; }
trap - ERR INT TERM
echo "部署成功：$PUBLIC_ORIGIN"
echo "提交：$SOURCE_COMMIT"
echo "当前版本：$RELEASE_DIR"
echo "旧版本：$PREVIOUS_RELEASE"
echo "配置及数据库备份：$BACKUP_DIR"
